version: '2'
services:
    devox-app:
        image: devox
        external_links:
            - devox-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devox?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    devox-mysql:
        extends:
            file: mysql.yml
            service: devox-mysql
